name: 'Tasklist completed all checks'
on: 
  pull_request:
    types: [opened, reopened, edited]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: chromaui/task-completed-checker-action@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
